spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    driverClassName: org.h2.Driver
    platform: h2
    data: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect

    show-sql: true

  h2:
    console:
      enabled: true

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: batch



  batch:
    initialize-schema: always
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

debug: true

